-- Migration 005: events.kind — the relation kind an event contributes to (HOSTILE, COOPERATIVE,
-- ROLE, OWNERSHIP or NULL), written by the producers from kg.ontology.ACTIONS so the API and the
-- relations job no longer carry their own action→kind tables.
ALTER TABLE events ADD COLUMN IF NOT EXISTS kind text;
CREATE INDEX IF NOT EXISTS events_kind_idx ON events (kind);
UPDATE events SET kind = CASE action
  WHEN 'ATTACK' THEN 'HOSTILE' WHEN 'THREATEN' THEN 'HOSTILE' WHEN 'SANCTION' THEN 'HOSTILE' WHEN 'COERCE' THEN 'HOSTILE'
  WHEN 'ACCUSE' THEN 'HOSTILE' WHEN 'ARREST' THEN 'HOSTILE' WHEN 'PROTEST' THEN 'HOSTILE' WHEN 'REJECT' THEN 'HOSTILE'
  WHEN 'COOPERATE' THEN 'COOPERATIVE' WHEN 'AID' THEN 'COOPERATIVE' WHEN 'AGREE' THEN 'COOPERATIVE' WHEN 'MEET' THEN 'COOPERATIVE'
  WHEN 'VISIT' THEN 'COOPERATIVE' WHEN 'APPEAL' THEN 'COOPERATIVE'
  WHEN 'APPOINT' THEN 'ROLE' WHEN 'RESIGN' THEN 'ROLE' WHEN 'ELECT' THEN 'ROLE'
  WHEN 'ACQUIRE' THEN 'OWNERSHIP' WHEN 'INVEST' THEN 'OWNERSHIP' ELSE NULL END
WHERE kind IS NULL AND origin <> 'gdelt';
